---
title: "Räumliche Gleiderungsebenen - Bevölkerungszahlen"
author: "Marvin Reis"
date: "21 1 2022"
output:
  bookdown::html_document2:
    keep_md: true
    code_folding: hide
    number_sections: false
    fig_caption: true
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library("dplyr")
library("tidyr")
library(bookdown)
library(knitr)
library(haven)
library(readxl)

home <- getwd()
setwd(home)

destatis_2019 <- read_excel("Data/Referenz/31122019_Auszug_GV.xlsx", sheet = "Onlineprodukt_Gemeinden_311219") %>% mutate(Gemeindekennziffer = as.numeric(paste0(...3,...4,...5,...7)), Kreiskennziffer = as.numeric(paste0(...3,...4,...5)), Bevölkerung_2019 = as.numeric(...10), Gemeindename = ...8) %>% filter(Bevölkerung_2019 != is.na(NA)) %>% select(Gemeindekennziffer, Kreiskennziffer, Bevölkerung_2019, Gemeindename)

destatis_2018 <- read_excel("Data/Referenz/31122018_Auszug_GV.xlsx", sheet = "Onlineprodukt_Gemeinden_311218") %>% mutate(Gem_2018 = as.numeric(paste0(...3,...4,...5,...7)), Kreiskennziffer = as.numeric(paste0(...3,...4,...5)), Bevölkerung_2018 = as.numeric(...10)) %>% filter(Bevölkerung_2018 != is.na(NA)) %>% select(Gem_2018, Kreiskennziffer, Bevölkerung_2018)

umstieg <- read_excel("Data/Referenz/ref-gemeinden-2010-2020.xlsx", sheet = "2018-2019") %>% select(Gem_2018, Gem_2019)

destatis_2018 <- destatis_2018 %>% left_join(umstieg, by = "Gem_2018") %>% group_by(Gem_2019) %>% mutate(Bevölkerung_2018 = sum(Bevölkerung_2018)) %>% ungroup() %>% select(-Gem_2018) %>% unique() %>% rename(Gemeindekennziffer = Gem_2019)

destatis <- destatis_2018 %>% left_join(destatis_2019, by = c("Gemeindekennziffer", "Kreiskennziffer")) %>% unique() %>% filter(Bevölkerung_2019 != is.na(NA)) %>% mutate(Bevölkerung = round((Bevölkerung_2018 + Bevölkerung_2019)/2)) %>%
  select(-Bevölkerung_2018, -Bevölkerung_2019)

referenz_gvb <- read_excel("Data/Referenz/Referenz_1998_2019.xls", sheet = "Gemeinden-GVB") %>% rename(GVBKennziffer = gvb19, Gemeindekennziffer = gem19) %>% select(GVBKennziffer, Gemeindekennziffer)

referenz_ror_nuts <- read_excel("Data/Referenz/Referenz_1998_2019.xls", sheet = "KRS") %>% rename(Kreiskennziffer = krs19, `Raumordnungsregion Nr` = ROR11) %>% select(`Raumordnungsregion Nr`, Kreiskennziffer, NUTS2)

gesamt <- destatis %>% left_join(referenz_gvb, by = "Gemeindekennziffer") %>% left_join(referenz_ror_nuts, by = "Kreiskennziffer") %>% unique() %>% select(-Gemeindename)

saveRDS(gesamt, paste0("Outfiles/2022_v01.1/Bevölkerung.rds"))
```


```{r message=FALSE, warning=FALSE}
Gemeinden <- gesamt %>% select(Bevölkerung, Gemeindekennziffer) %>% unique() %>% filter(Bevölkerung > 0)

GVB <- gesamt %>% select(Bevölkerung, GVBKennziffer) %>% group_by(GVBKennziffer) %>% mutate(Bevölkerung = sum(Bevölkerung)) %>% ungroup() %>% unique() %>% filter(Bevölkerung > 0)

Kreis <- gesamt %>% select(Bevölkerung, Kreiskennziffer) %>% group_by(Kreiskennziffer) %>% mutate(Bevölkerung = sum(Bevölkerung)) %>% ungroup() %>% unique() %>% filter(Bevölkerung > 0)

ROR <- gesamt %>% select(Bevölkerung, `Raumordnungsregion Nr`) %>% group_by(`Raumordnungsregion Nr`) %>% mutate(Bevölkerung = sum(Bevölkerung)) %>% ungroup() %>% unique() %>% filter(Bevölkerung > 0)

NUTS2 <- gesamt %>% select(Bevölkerung, NUTS2) %>% group_by(NUTS2) %>% mutate(Bevölkerung = sum(Bevölkerung)) %>% ungroup() %>% unique() %>% filter(Bevölkerung > 0)


Tabelle_Bev <- cbind("Ebene" = "Gemeinden", "Anzahl" = nrow(Gemeinden), "Mittlere Bevölkerungszahl" = round(mean(Gemeinden$Bevölkerung)), "Minimum" = round(min(Gemeinden$Bevölkerung)), "Maximum" = round(max(Gemeinden$Bevölkerung)))

Tabelle_Bev <- rbind(Tabelle_Bev, cbind("Ebene" = "Gemeindeverbände (GVB)", "Anzahl" = nrow(GVB), "Mittlere Bevölkerungszahl" = round(mean(GVB$Bevölkerung)), "Minimum" = round(min(GVB$Bevölkerung)), "Maximum" = round(max(GVB$Bevölkerung))))

Tabelle_Bev <- rbind(Tabelle_Bev, cbind("Ebene" = "Kreise und kreisfreie Städte (Kreise)", "Anzahl" = nrow(Kreis), "Mittlere Bevölkerungszahl" = round(mean(Kreis$Bevölkerung)), "Minimum" = round(min(Kreis$Bevölkerung)), "Maximum" = round(max(Kreis$Bevölkerung))))

Tabelle_Bev <- rbind(Tabelle_Bev, cbind("Ebene" = "Raumordnungsregionen (ROR)", "Anzahl" = nrow(ROR), "Mittlere Bevölkerungszahl" = round(mean(ROR$Bevölkerung)), "Minimum" = round(min(ROR$Bevölkerung)), "Maximum" = round(max(ROR$Bevölkerung))))

Tabelle_Bev <- rbind(Tabelle_Bev, cbind("Ebene" = "NUTS-2", "Anzahl" = nrow(NUTS2), "Mittlere Bevölkerungszahl" = round(mean(NUTS2$Bevölkerung)), "Minimum" = round(min(NUTS2$Bevölkerung)), "Maximum" = round(max(NUTS2$Bevölkerung))))

kable(Tabelle_Bev, caption = "Räumliche Gliederungsebenen in Deutschland und ihre Bevölkerungszahlen")
```