---
title: "GISD_Vergleiche"
author: "Marvin Reis"
date: "10 6 2021"
output:
  bookdown::html_document2:
    keep_md: true
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: false
    theme: cerulean
    highlight: tango
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("ggplot2")
library("rkicolors")
library("dplyr")
library("dtplyr")
library("tidyr")
library(haven)
library(broom)
library(knitr)
library(readxl)

home <- getwd()
setwd(home)
```

```{r Daten einlesen, message=FALSE, warning=FALSE}
dat_2018 <- read_dta("Outfiles/2018/Bund/Gemeinde/Gemeinde_long.dta") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)

dat_2020 <- read.csv("Outfiles/2020/Bund/Gemeinde/Gemeinde.csv") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)

dat_2021 <- read.csv("Outfiles/2021/Bund/Gemeinde/Gemeinde.csv") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)

dat_2021_v2 <- read.csv("Outfiles/2021_v2/Bund/Gemeinde/Gemeinde.csv") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)

dat_2021_v3 <- read.csv("Outfiles/2021_v3/Bund/Gemeinde/Gemeinde.csv") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)

dat_2022 <- read.csv("Outfiles/2022/Bund/Gemeinde/Gemeinde.csv") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)

dat_2022b <- read.csv("Outfiles/2022b/Bund/Gemeinde/Gemeinde.csv") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)

dat_2022_v3 <- read.csv("Outfiles/2022_v03/Bund/Gemeinde/Gemeinde.csv") %>% mutate(Kreis = round(Gemeindekennziffer/1000), digits = 0)



Lebenserwartung_Frauen <- read_excel("Data/Lebenserwartung/Lebenserwartung_female_13_17.xlsx", skip = 1, sheet = "Daten")
names(Lebenserwartung_Frauen)[1] <- "Kreis"
Lebenserwartung_Frauen[2:3] <- NULL
Lebenserwartung_Frauen <- Lebenserwartung_Frauen %>% gather(key = "Jahr", value = "Value" , -"Kreis", convert=T, na.rm = T) %>% mutate(Kreis = as.numeric(Kreis))

Lebenserwartung_Frauen_2014 <- Lebenserwartung_Frauen %>% filter(Jahr < 2016) %>% group_by(Kreis) %>% mutate(Lebenserwartung_Frauen_2014 = mean(Value)) %>% ungroup() %>% filter(Jahr == 2014) %>% select(Kreis,Lebenserwartung_Frauen_2014)
                                                                                                             
Lebenserwartung_Frauen_2016 <- Lebenserwartung_Frauen %>% filter(Jahr > 2014) %>% group_by(Kreis) %>% mutate(Lebenserwartung_Frauen_2016 = mean(Value)) %>% ungroup() %>% filter(Jahr == 2016) %>% select(Kreis,Lebenserwartung_Frauen_2016)

Lebenserwartung_Frauen <- Lebenserwartung_Frauen_2014 %>% left_join(Lebenserwartung_Frauen_2016, by = "Kreis")


Lebenserwartung_Männer <- read_excel("Data/Lebenserwartung/Lebenserwartung_male_13_17.xlsx", skip = 1, sheet = "Daten")
names(Lebenserwartung_Männer)[1] <- "Kreis"
Lebenserwartung_Männer[2:3] <- NULL
Lebenserwartung_Männer <- Lebenserwartung_Männer %>% gather(key = "Jahr", value = "Value" , -"Kreis", convert=T, na.rm = T) %>% mutate(Kreis = as.numeric(Kreis))

Lebenserwartung_Männer_2014 <- Lebenserwartung_Männer %>% filter(Jahr < 2016) %>% group_by(Kreis) %>% mutate(Lebenserwartung_Männer_2014 = mean(Value)) %>% ungroup() %>% filter(Jahr == 2014) %>% select(Kreis,Lebenserwartung_Männer_2014)
                                                                                                             
Lebenserwartung_Männer_2016 <- Lebenserwartung_Männer %>% filter(Jahr > 2014) %>% group_by(Kreis) %>% mutate(Lebenserwartung_Männer_2016 = mean(Value)) %>% ungroup() %>% filter(Jahr == 2016) %>% select(Kreis,Lebenserwartung_Männer_2016)

Lebenserwartung_Männer <- Lebenserwartung_Männer_2014 %>% left_join(Lebenserwartung_Männer_2016, by = "Kreis")

dat_Lebenserwartung <- Lebenserwartung_Frauen %>% left_join(Lebenserwartung_Männer, by = "Kreis")


rm(Lebenserwartung_Frauen, Lebenserwartung_Frauen_2014, Lebenserwartung_Frauen_2016, Lebenserwartung_Männer, Lebenserwartung_Männer_2014, Lebenserwartung_Männer_2016)



dat_Leberw_2018 <- dat_2018 %>% filter(Jahr == 2014) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2016, - Lebenserwartung_Männer_2016) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

dat_Leberw_2020 <- dat_2020 %>% filter(Jahr == 2016) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2014, - Lebenserwartung_Männer_2014) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

dat_Leberw_2021 <- dat_2021 %>% filter(Jahr == 2016) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2014, - Lebenserwartung_Männer_2014) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

dat_Leberw_2021_v2 <- dat_2021_v2 %>% filter(Jahr == 2016) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2014, - Lebenserwartung_Männer_2014) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

dat_Leberw_2021_v3 <- dat_2021_v3 %>% filter(Jahr == 2016) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2014, - Lebenserwartung_Männer_2014) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

dat_Leberw_2022 <- dat_2022 %>% filter(Jahr == 2016) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2014, - Lebenserwartung_Männer_2014) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

dat_Leberw_2022b <- dat_2022b %>% filter(Jahr == 2016) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2014, - Lebenserwartung_Männer_2014) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

dat_Leberw_2022_v3 <- dat_2022_v3 %>% filter(Jahr == 2016) %>% left_join(dat_Lebenserwartung, by = "Kreis") %>% select(- Lebenserwartung_Frauen_2014, - Lebenserwartung_Männer_2014) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

Gemeindekennziffer <- c("9162000", "16053000", "7317000", "1001000", "14625020", "9188139")
```

```{r Normalization}
dat_Leberw_2018$GISD_Score <- (dat_Leberw_2018$GISD_Score -min(dat_Leberw_2018$GISD_Score ))/(max(dat_Leberw_2018$GISD_Score )-min(dat_Leberw_2018$GISD_Score))

dat_Leberw_2020$GISD_Score <- (dat_Leberw_2020$GISD_Score -min(dat_Leberw_2020$GISD_Score ))/(max(dat_Leberw_2020$GISD_Score )-min(dat_Leberw_2020$GISD_Score))

dat_Leberw_2021$GISD_Score <- (dat_Leberw_2021$GISD_Score -min(dat_Leberw_2021$GISD_Score ))/(max(dat_Leberw_2021$GISD_Score )-min(dat_Leberw_2021$GISD_Score))

dat_Leberw_2021_v2$GISD_Score <- (dat_Leberw_2021_v2$GISD_Score -min(dat_Leberw_2021_v2$GISD_Score ))/(max(dat_Leberw_2021_v2$GISD_Score )-min(dat_Leberw_2021_v2$GISD_Score))

dat_Leberw_2021_v3$GISD_Score <- (dat_Leberw_2021_v3$GISD_Score -min(dat_Leberw_2021_v3$GISD_Score ))/(max(dat_Leberw_2021_v3$GISD_Score )-min(dat_Leberw_2021_v3$GISD_Score))

dat_Leberw_2022$GISD_Score <- (dat_Leberw_2022$GISD_Score -min(dat_Leberw_2022$GISD_Score ))/(max(dat_Leberw_2022$GISD_Score )-min(dat_Leberw_2022$GISD_Score))

dat_Leberw_2022b$GISD_Score <- (dat_Leberw_2022b$GISD_Score -min(dat_Leberw_2022b$GISD_Score ))/(max(dat_Leberw_2022b$GISD_Score )-min(dat_Leberw_2022b$GISD_Score))

dat_Leberw_2022_v3$GISD_Score <- (dat_Leberw_2022_v3$GISD_Score -min(dat_Leberw_2022_v3$GISD_Score ))/(max(dat_Leberw_2022_v3$GISD_Score )-min(dat_Leberw_2022_v3$GISD_Score))
```

## Versionen des GISD-Scores über die Zeit {.tabset}

### München
```{r München}
Tabelle_GISD_München <- cbind("Jahr" = "1998", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1998" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "9162000"])

                              
Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "1999", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2000", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2001", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2002", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2003", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "9162000"],

                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2004", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2005", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "9162000"],

                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2006", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2007", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2008", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2009", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2010", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2011", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2012", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2013", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2014", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2015", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2016", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2016" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- rbind(Tabelle_GISD_München, cbind("Jahr" = "2017", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "9162000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "9162000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "9162000"]))


Tabelle_GISD_München <- Tabelle_GISD_München %>% as_tibble()
kable(Tabelle_GISD_München)
```

### Flensburg
```{r Flensburg}
Tabelle_GISD_Flensburg <- cbind("Jahr" = "1998", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1998" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "1001000"])

                              
Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "1999", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2000", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2001", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2002", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2003", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2004", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2005", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2006", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2007", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2008", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2009", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2010", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2011", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2012", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2013", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2014", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2015", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2016", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2016" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- rbind(Tabelle_GISD_Flensburg, cbind("Jahr" = "2017", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "1001000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "1001000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "1001000"]))


Tabelle_GISD_Flensburg <- Tabelle_GISD_Flensburg %>% as_tibble()
kable(Tabelle_GISD_Flensburg)

```

### Jena
```{r Jena}
Tabelle_GISD_Jena <- cbind("Jahr" = "1998", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1998" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "16053000"])

                              
Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "1999", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2000", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2001", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2002", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2003", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2004", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2005", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2006", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2007", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2008", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2009", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2010", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2011", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2012", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2013", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2014", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2015", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2016", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2016" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- rbind(Tabelle_GISD_Jena, cbind("Jahr" = "2017", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "16053000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "16053000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "16053000"]))


Tabelle_GISD_Jena <- Tabelle_GISD_Jena %>% as_tibble()
kable(Tabelle_GISD_Jena)
```


### Pirmasens
```{r Pirmasens}
Tabelle_GISD_Pirmasens <- cbind("Jahr" = "1998", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1998" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "7317000"])

                              
Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "1999", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2000", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2001", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2002", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2003", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2004", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2005", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2006", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2007", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2008", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2009", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2010", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2011", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2012", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2013", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2014", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2015", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2016", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2016" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- rbind(Tabelle_GISD_Pirmasens, cbind("Jahr" = "2017", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "7317000"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "7317000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "7317000"]))


Tabelle_GISD_Pirmasens <- Tabelle_GISD_Pirmasens %>% as_tibble()
kable(Tabelle_GISD_Pirmasens)
```


### Bautzen
```{r Bautzen}
Tabelle_GISD_Bautzen <- cbind("Jahr" = "1998", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1998" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "14625020"])

                              
Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "1999", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2000", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2001", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2002", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2003", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2004", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2005", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2006", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2007", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2008", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2009", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2010", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2011", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2012", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2013", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2014", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2015", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2016", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2016" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- rbind(Tabelle_GISD_Bautzen, cbind("Jahr" = "2017", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "14625020"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "14625020"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "14625020"]))


Tabelle_GISD_Bautzen <- Tabelle_GISD_Bautzen %>% as_tibble()
kable(Tabelle_GISD_Bautzen)
```

### Starnberg
```{r Starnberg}
Tabelle_GISD_Starnberg <- cbind("Jahr" = "1998", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1998" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1998" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1998" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1998" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "9188139"])

                              
Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "1999", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1999" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1999" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2000", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2000" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2000" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2001", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2001" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2001" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2002", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2002" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2002" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2003", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2003" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2003" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2004", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2004" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2004" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2005", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2005" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2005" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2006", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2006" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2006" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2007", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2007" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2007" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2008", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2008" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2008" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2009", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2009" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2009" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2010", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2010" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2010" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2011", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2011" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2011" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2012", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2012" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2012" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2013", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2013" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2013" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2014", "GISD-Score V2018" = round(dat_2018$GISD_Score[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2014" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2014" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2015", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2015" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2015" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2016", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2016" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2016" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2016" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- rbind(Tabelle_GISD_Starnberg, cbind("Jahr" = "2017", "GISD-Score V2018" = "-", "Perzentil V2018" = "-",
                              
                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2017" & dat_2020$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2017" & dat_2021$Gemeindekennziffer == "9188139"],
                              
                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "9188139"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "9188139"]))


Tabelle_GISD_Starnberg <- Tabelle_GISD_Starnberg %>% as_tibble()
kable(Tabelle_GISD_Starnberg)
```


### Berlin
```{r Berlin}
#Tabelle_GISD_Berlin <- cbind(
#                            "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "1998" & dat_2015$Kreis #== "11000"], digits = 2), "Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "1998" & dat_2015$Gemeindekennziffer #== "11000"], digits = 2)
#                             "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1998" & #dat_2020$Gemeindekennziffer == "11000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1998" & #dat_2020$Gemeindekennziffer == "11000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1998" & #dat_2021$Gemeindekennziffer == "11000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1998" & #dat_2021$Gemeindekennziffer == "11000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1998" & #dat_2021_v2$Gemeindekennziffer == "11000"], digits = 2), "Perzentil V2021_v2" = dat_2021_v2$GISD_10[dat_2021_v2$Jahr #== "1998" & dat_2021_v2$Gemeindekennziffer == "11000"])
#
#                              
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "1999", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "1999" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "1999" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "1999" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "1999" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "1999" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "1999" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "1999" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "1999" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "1999" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2000", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2000" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2000" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2000" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2000" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2000" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2000" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2000" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2000" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2000" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2001", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2001" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2001" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2001" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2001" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2001" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2001" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2001" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2001" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2001" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2002", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2002" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2002" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2002" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2002" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2002" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2002" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2002" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2002" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2002" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2003", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2003" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2003" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2003" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2003" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2003" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2003" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2003" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2003" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2003" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2004", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2004" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2004" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2004" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2004" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2004" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2004" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2004" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2004" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2004" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2005", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2005" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2005" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2005" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2005" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2005" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2005" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2005" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2005" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2005" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2006", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2006" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2006" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2006" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2006" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2006" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2006" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2006" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2006" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2006" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2007", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2007" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2007" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2007" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2007" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2007" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2007" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2007" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2007" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2007" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2008", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2008" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2008" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2008" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2008" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2008" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2008" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2008" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2008" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2008" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2009", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2009" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2009" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2009" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2009" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2009" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2009" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2009" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2009" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2009" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2010", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2010" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2010" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2010" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2010" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2010" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2010" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2010" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2010" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2010" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2011", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2011" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2011" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2011" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2011" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2011" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2011" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2011" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2011" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2011" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2012", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2012" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2012" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2012" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2012" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2012" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2012" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2012" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2012" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2012" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2013", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2013" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2013" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2013" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2013" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2013" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2013" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2013" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2013" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2013" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2014", "GISD-Score V2018" = #round(dat_2018$GISD_Score[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "11000000"], digits = 2), #"Perzentil V2018" = dat_2018$GISD_10[dat_2018$Jahr == "2014" & dat_2018$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2014" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2014" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2014" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2014" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2014" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2014" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2014" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2014" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2015", "GISD-Score V2018" = "-", "Perzentil V2018" = #"-",
#                              
#                              "GISD-Score V2019" = round(dat_2015$GISD_Score[dat_2015$Jahr == "2015" & #dat_2015$Gemeindekennziffer == "11000000"], digits = 2),"Perzentil V2019" = dat_2015$GISD_10[dat_2015$Jahr == "2015" & #dat_2015$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2015" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2015" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2015" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2015" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2015" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2016", "GISD-Score V2018" = "-", "Perzentil V2018" = #"-",
#                              
#                              "GISD-Score V2019" = "-","Perzentil V2019" = "-",
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2016" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2016" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2016" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2016" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2016" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2015" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- rbind(Tabelle_GISD_Berlin, cbind("Jahr" = "2017", "GISD-Score V2018" = "-", "Perzentil V2018" = #"-",
#                              
#                              "GISD-Score V2019" = "-","Perzentil V2019" = "-",
#                              
#                              "GISD-Score V2020" = round(dat_2020$GISD_Score[dat_2020$Jahr == "2017" & #dat_2020$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2020" = dat_2020$GISD_10[dat_2020$Jahr == "2017" #& dat_2020$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021" = round(dat_2021$GISD_Score[dat_2021$Jahr == "2017" & #dat_2021$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021" = dat_2021$GISD_10[dat_2021$Jahr == "2017" #& dat_2021$Gemeindekennziffer == "11000000"],
#                              
#                              "GISD-Score V2021_v2" = round(dat_2021_v2$GISD_Score[dat_2021_v2$Jahr == "2017" & #dat_2021_v2$Gemeindekennziffer == "11000000"], digits = 2), "Perzentil V2021_v2" = #dat_2021_v2$GISD_10[dat_2021_v2$Jahr == "2017" & dat_2021_v2$Gemeindekennziffer == "11000000"]))
#
#
#Tabelle_GISD_Berlin <- Tabelle_GISD_Berlin %>% as_tibble()
#kable(Tabelle_GISD_Berlin)
```

## Lebenserwartung der Landkreise nach dem GISD in den verschiedenen Versionen {.tabset}

### V2018
```{r 2018, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2018) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2014, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2014, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2014), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2014), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (V2018)", subtitle = "im Jahr 2014, nach Geschlecht, mit Regressionslinie (Linear)",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()
```

### V2020
```{r 2020, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2020) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (V2020)", subtitle = "im Jahr 2016, nach Geschlecht, mit Regressionslinie (Linear)",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()
```

### V2021
```{r 2021, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2021) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (V2021)", subtitle = "im Jahr 2016, nach Geschlecht, mit Regressionslinie (Linear)",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()
```

### V2021_v2
```{r 2021_v2, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2021_v2) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (V2021_v2)", subtitle = "im Jahr 2016, nach Geschlecht, mit Regressionslinie (Linear)",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()
```

### V2021_v3
```{r 2021_v3, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2021_v3) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (V2021_v3)", subtitle = "im Jahr 2016, nach Geschlecht, mit Regressionslinie (Linear)",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()
```

### V2022
```{r V2022, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2022) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (V2022)", subtitle = "im Jahr 2016, nach Geschlecht, mit Regressionslinie (Linear)",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()
```

```{r V2022b, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2022b) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (V2022b)", subtitle = "im Jahr 2016, nach Geschlecht, mit Regressionslinie (Linear)",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()
```

```{r V2022_v3, message=FALSE, warning=FALSE}
ggplot(dat_Leberw_2022_v3) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016, col = "navy"), size = 1.5, alpha = 0.5) +
  geom_point(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016, col = "darkgreen"), size = 1.5, alpha = 0.5) +
  ylim(74, 88) +
  xlim(0, 1) +
  geom_rug(size = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Frauen_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  geom_smooth(aes(x = GISD_Score, y = Lebenserwartung_Männer_2016), method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score",
       y = "Lebenserwartung in Jahren") +
  scale_colour_identity(name = "Geschlecht", labels = c("Männer", "Frauen"),  guide = guide_legend(reverse = TRUE)) +
  theme_rki()

write.csv(dat_Leberw_2022_v3,"Outfiles/2022_v03/Lebenserwartung_GISD_2022_v03.csv")
```


## Änderungen in der Generierung des GISD

```{r}
Tab_Änderungen <- cbind("Version" = "2018", "Anpassungen" = "- Imputation fehlender Werte")

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "2020", "Anpassungen" = "- Imputation fehlender Werte"))

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "2021", "Anpassungen" = "- Imputation fehlender Werte"))

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "", "Anpassungen" = "- Anpassung an bildungspolitische Einflüsse (G8)"))

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "2021_v2", "Anpassungen" = "- Imputation fehlender Werte"))

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "", "Anpassungen" = "- Anpassung an bildungspolitische Einflüsse (G8)"))
                                              
Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "", "Anpassungen" = "- Sensibilisierung auf Ost-West Unterschiede"))

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "", "Anpassungen" = "- Deckelung der Beschäftigtenquote"))

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "", "Anpassungen" = "- Anpassung an Verbraucherpreisindex"))

Tab_Änderungen <- rbind(Tab_Änderungen, cbind("Version" = "", "Anpassungen" = "- Logarithmierung Einkommensteuer, Bruttoeinkommen und Haushaltseinkommen"))



kable(Tab_Änderungen)
```



