---
title: "Scatterplots - Lebenserwartung und Sozio-Ökonomische Deprivation"
author: "Marvin Reis"
date: "21 5 2021"
output:
  bookdown::html_document2:
    keep_md: true
    code_folding: hide
    number_sections: false
    fig_caption: true
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("ggplot2")
library("rkicolors")
library("tidyverse")
library("readxl")

home <- getwd()
setwd(home)
```


```{r message=FALSE, warning=FALSE}
Lebenserwartung_dat <- read_excel("Data/Lebenserwartung/Lebenserwartung_17_18_19.xlsx", skip = 1, sheet = "Daten")
names(Lebenserwartung_dat)[1] <- "Kreis"
Lebenserwartung_dat[2:3] <- NULL
Lebenserwartung_dat <- Lebenserwartung_dat %>% gather(key = "Jahr", value = "Value" , -"Kreis", convert=T, na.rm = T) %>% mutate(Kreis = as.numeric(Kreis))

Lebenserwartung_dat <- Lebenserwartung_dat %>% group_by(Kreis) %>% mutate(Lebenserwartung = mean(Value)) %>% ungroup() %>% filter(Jahr == 2018) %>% select(-Jahr, -Value)

GISD_data_Kreis <- read.csv("Outfiles/2022/Bund/Kreis/Kreis.csv") %>% filter(Jahr == 2018)

GISD_data_Kreis <- GISD_data_Kreis %>% mutate(Kreis = Kreiskennziffer) %>% select(Kreis, GISD_Score) %>% distinct(Kreis, .keep_all = TRUE) %>% unique()

GISD_Lebenserw_Kreis <- left_join(GISD_data_Kreis, Lebenserwartung_dat, by = "Kreis")
```

```{r}
#Normalization
GISD_Lebenserw_Kreis$GISD_Score <- (GISD_Lebenserw_Kreis$GISD_Score -min(GISD_Lebenserw_Kreis$GISD_Score ))/(max(GISD_Lebenserw_Kreis$GISD_Score )-min(GISD_Lebenserw_Kreis$GISD_Score ))
```

```{r}
ggplot(GISD_Lebenserw_Kreis, aes(x = GISD_Score, y = Lebenserwartung)) +
  geom_point(size = 1.5, alpha = 0.5, col = "navy") +
  geom_rug(size = 0.5) + 
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD", subtitle = "auf Basis 2018", y = "Lebenserwartung in Jahren") +
  theme_rki()
```

```{r}
ggplot(GISD_Lebenserw_Kreis, aes(x = GISD_Score, y = Lebenserwartung)) +
  geom_point(size = 1.5, alpha = 0.5, col = "navy") +
  geom_rug(size = 0.5) +
  geom_smooth(method = loess, col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD", subtitle =  "auf Basis 2018, mit Regressionslinie (Loess)", y = "Lebenserwartung in Jahren") +
  theme_rki()
```

```{r}
ggplot(GISD_Lebenserw_Kreis, aes(x = GISD_Score, y = Lebenserwartung)) +
  geom_point(size = 1.5, alpha = 0.5, col = "navy") +
  geom_rug(size = 0.5) +
  geom_smooth(method = lm,col = "red", linetype = "dashed", fill = "grey50", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD", subtitle = "auf Basis 2018, mit Regressionslinie (Linear)", y = "Lebenserwartung in Jahren") +
  theme_rki()
```

```{r}
ggplot(GISD_Lebenserw_Kreis, aes(x = GISD_Score, y = Lebenserwartung)) +
  geom_point(size = 1, alpha = 0.5) +
  geom_density2d(size = 1, col = "navy", alpha = 0.5) +
  labs(x = "GISD-Score", title = "Lebenserwartung der Landkreise nach dem GISD (Density)", subtitle = "auf Basis 2018", y = "Lebenserwartung in Jahren") +
  theme_rki()
```


```{r message=FALSE, warning=FALSE}
GISD_dat <- read.csv("Outfiles/2022/Bund/Kreis/Kreis.csv") %>% select(GISD_5, Jahr, Kreiskennziffer) %>% rename(Kreis = Kreiskennziffer) %>% mutate(GISD_5 = case_when(GISD_5 == 1 ~ 5,
                                               GISD_5 == 2 ~ 4,
                                               GISD_5 == 3 ~ 3,
                                               GISD_5 == 4 ~ 2,
                                               GISD_5 == 5 ~ 1))



##Datenaufbereitung der Frauen Daten
Lebenserwartung_female <- read_excel("Data/Lebenserwartung/Lebenserwartung_female_97_17.xlsx", skip = 1, sheet = "Daten")
names(Lebenserwartung_female)[1] <- "Kreis"
Lebenserwartung_female[2:3] <- NULL
Lebenserwartung_female <- Lebenserwartung_female %>% gather(key = "Jahr", value = "Value" , -"Kreis", convert=T, na.rm = T) %>% mutate(Kreis = as.numeric(Kreis))

Lebenserwartung_Kreise <- Lebenserwartung_female %>% select(Kreis)

for (i in 1998:2016) {
Lebenserwartung <- Lebenserwartung_female %>% group_by(Kreis) %>% filter(Jahr == i | Jahr == i+1 | Jahr == i-1) %>% mutate(Lebenserwartung_adj = mean(Value)) %>% ungroup() %>% filter(Jahr == i) %>% select(-Value)

Lebenserwartung <- spread(Lebenserwartung, key = Jahr, value = Lebenserwartung_adj)

Lebenserwartung_Kreise <- Lebenserwartung_Kreise %>% left_join(Lebenserwartung, by = c("Kreis"))
}

Lebenserwartung_female_mean <- gather(Lebenserwartung_Kreise, key = "Jahr", value = "Lebenserwartung_adj", 2:20) %>% mutate(Jahr = as.numeric(Jahr))

Lebenserwartung_female_mean <- Lebenserwartung_female_mean %>% left_join(GISD_dat, by = c("Kreis", "Jahr")) %>% group_by(GISD_5, Jahr) %>% mutate(Lebenserwartung_mean = mean(Lebenserwartung_adj)) %>% ungroup()


##Datenaufbereitung der Männer Daten
Lebenserwartung_male <- read_excel("Data/Lebenserwartung/Lebenserwartung_male_97_17.xlsx", skip = 1, sheet = "Daten")
names(Lebenserwartung_male)[1] <- "Kreis"
Lebenserwartung_male[2:3] <- NULL
Lebenserwartung_male <- Lebenserwartung_male %>% gather(key = "Jahr", value = "Value" , -"Kreis", convert=T, na.rm = T) %>% mutate(Kreis = as.numeric(Kreis))

Lebenserwartung_Kreise <- Lebenserwartung_male %>% select(Kreis)

for (i in 1998:2016) {
Lebenserwartung <- Lebenserwartung_male %>% group_by(Kreis) %>% filter(Jahr == i | Jahr == i+1 | Jahr == i-1) %>% mutate(Lebenserwartung_adj = mean(Value)) %>% ungroup() %>% filter(Jahr == i) %>% select(-Value)

Lebenserwartung <- spread(Lebenserwartung, key = Jahr, value = Lebenserwartung_adj)

Lebenserwartung_Kreise <- Lebenserwartung_Kreise %>% left_join(Lebenserwartung, by = c("Kreis"))
}

Lebenserwartung_male_mean <- gather(Lebenserwartung_Kreise, key = "Jahr", value = "Lebenserwartung_adj", 2:20) %>% mutate(Jahr = as.numeric(Jahr))

Lebenserwartung_male_mean <- Lebenserwartung_male_mean %>% left_join(GISD_dat, by = c("Kreis", "Jahr")) %>% group_by(GISD_5, Jahr) %>% mutate(Lebenserwartung_mean = mean(Lebenserwartung_adj)) %>% ungroup()

```

```{r}
ggplot(Lebenserwartung_female_mean, aes(x = Jahr, y = Lebenserwartung_mean, col = as.factor(GISD_5))) +
  geom_line(size = 1.25) +
  geom_point() +
  scale_color_rki(labels = c("5", "4", "3", "2", "1"), guide = guide_legend(reverse=TRUE)) +
  labs(title = "Lebenserwartung von Frauen über die Jahre nach GISD-Quintil", y = "Durchschnittliche Lebenserwartung", col = "GISD-Quintil") +
  theme_rki()
```

```{r}
ggplot(Lebenserwartung_male_mean, aes(x = Jahr, y = Lebenserwartung_mean, col = as.factor(GISD_5))) +
  geom_line(size = 1.25) +
  geom_point() +
  scale_color_rki(labels = c("5", "4", "3", "2", "1"), guide = guide_legend(reverse=TRUE)) +
  labs(title = "Lebenserwartung von Männern über die Jahre nach GISD-Quintil", y = "Durchschnittliche Lebenserwartung", col = "GISD-Quintil") +
  theme_rki()
```

